backbone: SigmaMUNet
backbone_specs:
  activation: ELU
  activation_bg: sigmoid
  activation_phot: sigmoid
  activation_prob: sigmoid
  activation_sig: sigmoid
  activation_xyz: tanh
  depth:
  depth_shared: 2
  depth_union: 2
  depth_bg:
  init_custom: true
  initial_features: 48
  initial_features_bg:
  inter_features: 48
  norm:
  norm_bg:
  norm_bg_groups:
  norm_groups:
  norm_head:
  norm_head_groups:
  p_dropout:
  pool_mode: StrideConv
  upsample_mode: nearest
  recpt_bg:
  skip_gn_level:
  up_mode: upsample
  use_last_nl:

aux_shared: true
aux_union: false
ch_in_map: null  # old model
ch_out_heads: null  # old model
separate_ch: false
separate_win: true
